### PR TITLE
Add info about F# and other alternatives to C#

### PR DESCRIPTION
**Pull request by ShalokShalom**
Add info about F# and other alternatives to C#

### CODE REVIEW

**Comment by ShalokShalom** [comment]
done

**Comment by ddobrev** [comment]
@ShalokShalom my apologies, I should've explained better. What you added is a comment to the pull request. What I am asking for is to change the message to your Git commit. When you do, please amend your top commit and force push.

**Comment by ShalokShalom** [comment]
Can you do this by your own? I currently see myself confused with this. xD

**Comment by ddobrev** [comment]
@ShalokShalom of course, no problem.

**Comment by ShalokShalom** [comment]
thanks a lot

**Pull request closed without merging**
