### PR TITLE
Some changes for references / logging to a text file / how to build uitools

### PR DESCRIPTION
**Pull request by grbd**
Added a couple of small changes, not sure if you want to add all of these in
but some might be usefull

 * Added a couple of missing references to QtSharp.CLI for Compression
 * Added Nuget packages subdir to .gitignore 
 * Added a simple console redirect for logging to a logs subdirectory for each module
 * Added a doc on building out uitools

A better option for logging might be something like common logging https://github.com/net-commons/common-logging
but that would require lots of changes to CppSharp, so the above changes just redirect the console to a seperate log file for each module

### CODE REVIEW

**Comment by ddobrev** [comment]
I actually meant for you to amend your commits, not apply new ones on top. I know this would cause you some trouble with rebasing but I'd rather have the commits clean in the first place instead of being fixed afterwards.

**Comment by grbd** [comment]
Okay no probs I'll probably just re-fork the repo and redo the commits, I didn't know you could ammend commits afterwards

**Comment by ddobrev** [comment]
Well, you don't actually need to, just amend/rebase/etc and then force push.

**Comment by grbd** [comment]
yep that's what I'm going to do, I just didn't realise you could rebase an amend commits before now

**Pull request closed without merging**
